var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/campaigns/[id]/sessions/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__036x4o2._.js")
R.c("server/chunks/ssr/node_modules_05l396c._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_016n60d.js")
R.c("server/chunks/ssr/[root-of-the-server]__00phxzs._.js")
R.c("server/chunks/ssr/[root-of-the-server]__098zro9._.js")
R.c("server/chunks/ssr/app_layout_tsx_13yf0ls._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_campaigns_[id]_sessions_page_actions_0dch6bz.js")
R.m(23351)
module.exports=R.m(23351).exports
